### ISSUE TITLE
NOT_OPTIMIZED not defined in all cases

### ISSUE THREAD

**Issue by clemahieu** [khovratovich/Argon2#11]
In argon2-core.cpp there some cases where NOT_OPTIMIZED is not defined.

defined(**clang**) && !**has_attribute(optnone)
!defined(__clang**) && defined(**GNUC**) && GCC_VERSION < 40400

By deleting:
# else
# define NOT_OPTIMIZED

You could place a catch-all block:
# ifndef NOT_OPTIMIZED
# define NOT_OPTIMIZED
# endif

**Comment by khovratovich** [comment]
Fixed
