### ISSUE TITLE
both C++11 and C99 Makefiles generate libargon2.so

### ISSUE THREAD

**Issue by Safari77** [khovratovich/Argon2#17]
also `argon2.h` could be renamed.  maybe for C++ `libargon2++.so` and `argon2++.h`.

**Comment by khovratovich** [comment]
Why the same name could be a problem? We intended to make implementations as close as possible

**Comment by Safari77** [comment]
Well, if for example Linux distros want to include libargon2, they have to use different filenames for C++11 and C99 versions.

**Comment by daniel-dinu** [comment]
Usually a single implementation/library should be enough.
In the case that there will be a C and a C++ version for the same library, the name conflict can be easily solved by using different paths.
