### ISSUE TITLE
Custom free function signature

### ISSUE THREAD

**Issue by clemahieu** [khovratovich/Argon2#5]
With the signature 
typedef void(*FreeMemoryCallback)(uint8_t *memory, size_t bytes_to_allocate);

It looks like this should be (uint8_t *memory, bool clear_memory) to match FreeMemory.

I'd also recommend clearing be done inside Finalize and drop the second parameter all together.

**Comment by khovratovich** [comment]
It should rather be typedef void(*FreeMemoryCallback)(uint8_t *memory, size_t bytes_to_allocate, bool clear_memory);

The second parameter is important as the custom memory deallocator does not know its size.

Your last sentence is unclear, could you elaborate?

**Comment by clemahieu** [comment]
Rather than letting telling the custom allocator whether to clear the memory, Finalize could clear the memory if needed and the clear_memory parameter wouldn't be needed.

**Comment by daniel-dinu** [comment]
Fixed with commit 561884f6d789e6e7238276f668fac26a4ed6cca5.

**Comment by khovratovich** [comment]
I suggest moving the Sbox deallocation out of ClearMemory().

**Comment by daniel-dinu** [comment]
Fix with commit fd4549c11f33b76db22c779d7f2aec2bcace8849
